### PR TITLE
Add bash script for Linux users

### PR DESCRIPTION
**Pull request by sinbad86**

### CODE REVIEW

**Review by kovimilu — COMMENTED** [review]
Looks good to me.
@MaciejGorczyca

**Comment by MaciejGorczyca** [comment]
Yeah, looks great. I guess you can run bash scripts on macOS as well, right? In theory it should work?

**Comment by kovimilu** [comment]
I have never used a mac, so i would rather not say anything :D

**Comment by sinbad86** [comment]
Oops, macOS support hadn't even occurred to me. I searched a little and it looks like macOS's shell doesn't have `pidof` by default. I changed the script a little in #17, but somebody will need to test it.

**Comment by MaciejGorczyca** [comment]
Thanks. I merged your update. It would be cool if someone had access to macOS and could test this for us but I guess we shouldn't really worry about this too much! If someone comes across this and has macOS support - give the script a try and let us know. 👍

**Pull request merged**
